schema:
  - card:
      appName: As Casamenteiras Fans TESTE ISSO PODE IR EMBORA ?
      version: "1.0.0"
      brandDescription: Assessoria e Cerimonial para casamentos, eventos corporativos e festas em geral.
      brandurl: /
      brandName: As Casamenteiras
      keywords:
        - key: As Casamenteiras
        - key: assessoria em eventos
        - key: cerimonialista
        - key: casamentos
        - key: cerimonial
        - key: cerimonialista ribeirão preto
        - key: casamenteiras
      sameAs:
        instagram: https://www.instagram.com/ascasamenteiras_
      alternateName: alllllright
      potentialAction: ReadAction
      telephone: "+551130420043"
      contactType: Serviço Ao Cliente
      email: cerimonial@ascasamenteiras.com.br
      inLanguage: 'pt-BR'
      datePublished: 04 de julho de 2022
