schema:
  - card:
      appName: As Casamenteiras Fans
      version: "1.0.0"
      brandDescription: App para fãs da As Casamenteiras.
      brandurl: /
      brandName: As Casamenteiras
      keywords:
        - key: As Casamenteiras
        - key: cursos
        - key: curso online
        - key: power skills
        - key: soft skills
        - key: habilidades
        - key: casamenteiras
      sameAs:
        facebook: https://www.facebook.com/ascasamenteiras_yml
        instagram: https://www.instagram.com/ascasamenteiras_yml
        linkedIn: https://br.linkedin.com/school/ascasamenteiras_yml
        youtube: https://www.youtube.com/c/ascasamenteiras_yml
      alternateName: a
      potentialAction: Learning
      telephone: "+551130420043"
      contactType: Serviço Ao Cliente
      email: cerimonial@ascasamenteiras.com.br
      inLanguage: 'pt-BR'
      datePublished: 05 de março de 2022
