schema:
  - card:
      appName: Simone Tebet Fans
      version: "1.0.0"
      brandDescription: App para fãs da Simone Tebet.
      brandurl: /
      brandName: Simone Tebet
      keywords:
        - key: simone tebet
        - key: cursos
        - key: curso online
        - key: power skills
        - key: soft skills
        - key: habilidades
        - key: tebet fans
      sameAs:
        facebook: https://www.facebook.com/tebetfans
        instagram: https://www.instagram.com/tebetfans
        linkedIn: https://br.linkedin.com/school/tebetfans
        youtube: https://www.youtube.com/c/tebetfans
      alternateName: a
      potentialAction: Learning
      telephone: "+551130420043"
      contactType: Serviço Ao Cliente
      email: contato@tebet.fans
      inLanguage: 'pt-BR'
      datePublished: 05 de março de 2022
